sudo: required
dist: trusty
language: bash

stages:
  - name: Script tests
  - name: Build test
    if: branch != master
  - name: Push container
    if: branch = master && type = pull_request
  - name: Check container
    if: branch = master || type = pull_request


services:
  - docker

install:
  - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse"
  - sudo apt-get -qq update
  - sudo apt-get -t trusty-backports install shellcheck
  - sudo pip install bashate

jobs:
  include:
  - stage: Script tests
    script:
      - echo ${TRAVIS_COMMIT}
      - echo ${TRAVIS_TAG}
      - echo ${TRAVIS_BRANCH}
      - echo ${TRAVIS_BUILD_NUMBER}
      - echo ${TRAVIS_REPO_SLUG}
      # test bash scripts
      - shellcheck scripts/*.sh
      - bashate scripts/*.sh

  - stage: Build test
    script:
      - docker build -t pylint .
      - testpath="$(pwd)/tests"
      - echo ${testpath}; docker run --rm -v ${testpath}:/pylint pylint --help
      # Add more tests here

  - stage: Push container
    script:
      - echo "push to repo"
      - BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      - VCS_REF=$(git rev-parse --short HEAD)
      - VER=$(cat VERSION)
      - docker build --build-arg BUILD_DATE=${BUILD_DATE} --build-arg VCS_REF=${VCS_REF} --build-arg VER=${VER} -t pylint .
      - docker images
      - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
      - docker tag pylint ${DOCKER_USERNAME}/pylint:default
      - docker push ${DOCKER_USERNAME}/pylint:default
      - curl -X POST https://hooks.microbadger.com/images/almerhor/imagemagick/XaAIxgDs-u9xmQELNid3BiJ-YxI=
      - docker logout

  - stage: Check container
    script:
      - docker pull ${DOCKER_USERNAME}/imagemagick
      - bucketpath="$(pwd)/tests/bucket"
      - docker run --rm -v ${bucketpath}:/bucket ${DOCKER_USERNAME}/imagemagick convert plant.jpg -resize 50% resized50.jpg
